-- MySQL Script generated by MySQL Workbench
-- Mon Oct 13 21:13:28 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Matias Store1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Matias Store1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Matias Store1` DEFAULT CHARACTER SET utf8 ;
USE `Matias Store1` ;

-- -----------------------------------------------------
-- Table `Matias Store1`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matias Store1`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(100) NOT NULL,
  `cpf_cliente` CHAR(11) NULL,
  `telefone_cliente` VARCHAR(20) NULL,
  `email_cliente` VARCHAR(100) NULL,
  `endereco_cliente` VARCHAR(100) NULL,
  `dt_nasc_cliente` DATE NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `cpf_cliente_UNIQUE` (`cpf_cliente` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matias Store1`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matias Store1`.`funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome_funcionario` VARCHAR(100) NOT NULL,
  `telefone_funcionario` VARCHAR(20) NULL,
  `email_funcionario` VARCHAR(100) NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matias Store1`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matias Store1`.`marca` (
  `id_marca` INT NOT NULL AUTO_INCREMENT,
  `nome_marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matias Store1`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matias Store1`.`modelo` (
  `id_modelo` INT NOT NULL AUTO_INCREMENT,
  `nome_modelo` VARCHAR(45) NOT NULL,
  `cor_modelo` VARCHAR(20) NULL,
  `tipo_modelo` VARCHAR(45) NULL,
  `marca_id_marca` INT NOT NULL,
  PRIMARY KEY (`id_modelo`, `marca_id_marca`),
  INDEX `fk_modelo_marca_idx` (`marca_id_marca` ASC) ,
  CONSTRAINT `fk_modelo_marca`
    FOREIGN KEY (`marca_id_marca`)
    REFERENCES `Matias Store1`.`marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matias Store1`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matias Store1`.`venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `data_venda` DATE NOT NULL,
  `valor_venda` DECIMAL(10,2) NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  `funcionario_id_funcionario` INT NOT NULL,
  `modelo_id_modelo` INT NOT NULL,
  PRIMARY KEY (`id_venda`, `cliente_id_cliente`, `funcionario_id_funcionario`, `modelo_id_modelo`),
  INDEX `fk_venda_cliente1_idx` (`cliente_id_cliente` ASC) ,
  INDEX `fk_venda_funcionario1_idx` (`funcionario_id_funcionario` ASC) ,
  INDEX `fk_venda_modelo1_idx` (`modelo_id_modelo` ASC) ,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `Matias Store1`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `Matias Store1`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_modelo1`
    FOREIGN KEY (`modelo_id_modelo`)
    REFERENCES `Matias Store1`.`modelo` (`id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
